### ISSUE TITLE
Not able to place object on a surface.It keeps moving along with the phone's movement.How to place this object on a surface after identifying it?

### ISSUE THREAD

**Issue by linuissac** [viromedia/ViroARSampleApp#5]

**Comment by dam00n** [comment]
@linuissac, the easiest way is to us ViroARPlaneSelector which will place your component on the plane once it is detected and tapped.

What device are you using? Are you seeing planes? Perhaps you are placing objects at a real world distance rather than on a plane. See this tutorial on how to add objects to planes -> https://blog.viromedia.com/how-to-build-an-interactive-ar-app-in-5-mins-w-react-native-viro-ar-e420147e1612

**Comment by linuissac** [comment]
[](https://github.com/viromedia/ViroARSampleApp/blob/master/js/ARHitTestSample.js) 
For this sample code , the problem i'm facing is it will detect only the floor as a surface i can't do it  anywhere else.

**Comment by linuissac** [comment]
@dam00n  , Actually the problem i'm facing for the below sample app is , it will detect only the floor as a surface , cannot place object anywhere else. It keeps moving if i place it on a table. But when i placed the same on floor it will detect the surface.
